### ISSUE TITLE
non-drive remotes

### ISSUE THREAD

**Issue by a5m0** [endevrr/AutoRclone-Rewrite#13]
I'm trying to use a google cloud storage remote but it looks like the config util can only handle drive remotes, is it possible to pass through non-drive remotes from the rclone config?

**Comment by ShiroUwUs7** [comment]
@a5m0 did you get this fixed at all?

**Comment by williamjohnstone** [comment]
This is not fixed, I will open a new enhancement issues for this
